name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.10'
    - uses: actions/checkout@v3
    - name: Build
      run: swift build --build-tests
    - name: Test
      run: swift test
