name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: '6.1'
    - uses: actions/checkout@v3
    - name: Build
      run: swift build --build-tests
    - name: Test
      run: swift test
